#include "soc_estimator.h"
#include "SOC_Model_AI_Prediction.h"   // generated by m2cgen or similar

float SOC_Estimator_Update(float voltage_V, float current_A, float temp_C)
{
    double input[3];

    input[0] = voltage_V;
    input[1] = current_A;
    input[2] = temp_C;

    double soc = score(input);   // XGBoost generated function

    if (soc < 0.0) soc = 0.0;
    if (soc > 100.0) soc = 100.0;

    return (float)soc;
}